repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8  # Use the latest version available
  hooks:
  - id: clang-format

- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
    - id: cppcheck
      args:
        - --enable=all
      files: '(src/.*\.c|src/structs/.*\.c)$'  # Match .c files in src and src/structs directories
